-- HoopSpot pradinis Supabase duomenų bazės pagrindas.

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 1 and 100),
  created_at timestamptz not null default timezone('utc', now())
);

create table public.activities (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references public.profiles (id) on delete restrict,
  title text not null check (char_length(trim(title)) between 1 and 160),
  description text not null default '' check (char_length(description) <= 5000),
  activity_type text not null check (char_length(trim(activity_type)) between 1 and 80),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  location text not null check (char_length(trim(location)) between 1 and 200),
  capacity integer not null check (capacity > 0),
  reserved_slots integer not null default 0 check (reserved_slots >= 0 and reserved_slots <= capacity),
  status text not null default 'active' check (status in ('active', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint activities_time_order check (ends_at > starts_at)
);

create table public.reservations (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities (id) on delete restrict,
  user_id uuid not null references public.profiles (id) on delete restrict,
  status text not null default 'active' check (status in ('active', 'cancelled')),
  reserved_at timestamptz not null default timezone('utc', now()),
  cancelled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  constraint reservations_cancelled_at_check check (
    (status = 'cancelled' and cancelled_at is not null)
    or (status = 'active' and cancelled_at is null)
  )
);

-- Indeksai viešam veiklų sąrašui, kūrėjo veikloms ir rezervacijoms.
create index activities_starts_at_idx on public.activities (starts_at);
create index activities_creator_id_idx on public.activities (creator_id);
create index reservations_user_id_idx on public.reservations (user_id);
create index reservations_activity_id_idx on public.reservations (activity_id);

-- Viena aktyvi rezervacija tam pačiam vartotojui vienoje veikloje.
create unique index reservations_one_active_per_user_idx
  on public.reservations (activity_id, user_id)
  where status = 'active';

-- Atnaujinimo laikas keičiamas automatiškai.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create trigger activities_set_updated_at
before update on public.activities
for each row execute function public.set_updated_at();

-- Talpa nustatoma kuriant veiklą ir vėliau nekeičiama.
create or replace function public.prevent_capacity_update()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if new.capacity is distinct from old.capacity then
    raise exception 'Veiklos capacity po sukūrimo keisti negalima';
  end if;
  return new;
end;
$$;

create trigger activities_capacity_immutable
before update on public.activities
for each row execute function public.prevent_capacity_update();

-- Naujam Auth vartotojui automatiškai sukuriamas profilis.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), split_part(coalesce(new.email, 'Vartotojas'), '@', 1))
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Saugus rezervavimas vienoje transakcijoje: veiklos eilutė užrakinama prieš tikrinimus.
create or replace function public.reserve_activity(p_activity_id bigint)
returns public.reservations
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  current_user_id uuid := auth.uid();
  activity_row public.activities;
  reservation_row public.reservations;
begin
  if current_user_id is null then
    raise exception 'Rezervavimui reikia prisijungti';
  end if;

  select * into activity_row
  from public.activities
  where id = p_activity_id
  for update;

  if not found then
    raise exception 'Veikla nerasta';
  end if;
  if activity_row.status <> 'active' then
    raise exception 'Veikla atšaukta';
  end if;
  if activity_row.starts_at <= timezone('utc', now()) then
    raise exception 'Veikla jau prasidėjo';
  end if;
  if activity_row.reserved_slots >= activity_row.capacity then
    raise exception 'Veikla pilna';
  end if;
  if exists (
    select 1 from public.reservations
    where reservations.activity_id = p_activity_id
      and reservations.user_id = current_user_id
      and reservations.status = 'active'
  ) then
    raise exception 'Šioje veikloje jau turite aktyvią rezervaciją';
  end if;

  insert into public.reservations (activity_id, user_id)
  values (p_activity_id, current_user_id)
  returning * into reservation_row;

  update public.activities
  set reserved_slots = reserved_slots + 1
  where id = p_activity_id;

  return reservation_row;
end;
$$;

-- Saugus tik savo aktyvios rezervacijos atšaukimas iki veiklos pradžios.
create or replace function public.cancel_reservation(p_reservation_id bigint)
returns public.reservations
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  current_user_id uuid := auth.uid();
  reservation_row public.reservations;
  activity_row public.activities;
  updated_reservation public.reservations;
begin
  if current_user_id is null then
    raise exception 'Rezervacijos atšaukimui reikia prisijungti';
  end if;

  select * into reservation_row
  from public.reservations
  where id = p_reservation_id
    and user_id = current_user_id
  for update;

  if not found then
    raise exception 'Rezervacija nerasta arba nepriklauso vartotojui';
  end if;
  if reservation_row.status <> 'active' then
    raise exception 'Rezervacija jau atšaukta';
  end if;

  select * into activity_row
  from public.activities
  where id = reservation_row.activity_id
  for update;

  if activity_row.starts_at <= timezone('utc', now()) then
    raise exception 'Prasidėjusios veiklos rezervacijos atšaukti negalima';
  end if;

  update public.reservations
  set status = 'cancelled', cancelled_at = timezone('utc', now())
  where id = p_reservation_id
  returning * into updated_reservation;

  update public.activities
  set reserved_slots = greatest(0, reserved_slots - 1)
  where id = activity_row.id;

  return updated_reservation;
end;
$$;

-- Klientui leidžiama kviesti tik saugias rezervavimo funkcijas.
revoke all on function public.reserve_activity(bigint) from public, anon;
revoke all on function public.cancel_reservation(bigint) from public, anon;
grant execute on function public.reserve_activity(bigint) to authenticated;
grant execute on function public.cancel_reservation(bigint) to authenticated;

-- Kliento teisės ribojamos stulpelių lygiu; SECURITY DEFINER funkcijų tai nevaržo.
revoke all on table public.profiles, public.activities, public.reservations from anon, authenticated;
grant select on table public.profiles to anon, authenticated;
grant select on table public.activities to anon, authenticated;
grant insert (creator_id, title, description, activity_type, starts_at, ends_at, location, capacity) on table public.activities to authenticated;
grant update (title, description) on table public.activities to authenticated;
grant select on table public.reservations to authenticated;
grant usage, select on all sequences in schema public to authenticated;
-- Įjungiame RLS visoms aplikacijos lentelėms.
alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.reservations enable row level security;

create policy profiles_select_public
  on public.profiles for select
  to anon, authenticated
  using (true);

create policy profiles_update_own
  on public.profiles for update
  to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

create policy activities_select_all
  on public.activities for select
  to anon, authenticated
  using (true);

create policy activities_insert_own
  on public.activities for insert
  to authenticated
  with check (
    creator_id = (select auth.uid())
    and reserved_slots = 0
    and status = 'active'
  );

create policy activities_update_own
  on public.activities for update
  to authenticated
  using (creator_id = (select auth.uid()))
  with check (creator_id = (select auth.uid()));

create policy reservations_select_own_or_activity_creator
  on public.reservations for select
  to authenticated
  using (
    user_id = (select auth.uid())
    or exists (
      select 1 from public.activities
      where activities.id = reservations.activity_id
        and activities.creator_id = (select auth.uid())
    )
  );

-- Rezervacijos keičiamos tik per SECURITY DEFINER funkcijas.
create policy reservations_insert_none
  on public.reservations for insert
  to authenticated
  with check (false);

create policy reservations_update_none
  on public.reservations for update
  to authenticated
  using (false)
  with check (false);

create policy reservations_delete_none
  on public.reservations for delete
  to authenticated
  using (false);




